apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: rdsmysql
spec:
  forProvider:
    dbInstanceClass: db.t2.small
    vpcSecurityGroupIDRefs:
    - name: sample-rds-sg
    dbSubnetGroupNameRef:
      name: sample-dbsubnetgroup
    masterUsername: masteruser
    allocatedStorage: 20
    engine: mysql
    publiclyAccessible: true
    applyModificationsImmediately: true
    skipFinalSnapshotBeforeDeletion: true
  writeConnectionSecretToRef:
    name: rds-secret
    namespace: crossplane-system
  providerRef:
    name: aws-provider
  reclaimPolicy: Delete