apiVersion: workload.crossplane.io/v1alpha1
kind: KubernetesApplication
metadata:
  name: capi-app
  labels:
    app: capi
spec:
  resourceSelector:
    matchLabels:
      tbs: eleven
  targetSelector:
    matchLabels:
      tbs: eleven
  resourceTemplates:
    - metadata:
        name: capi-namespace
        labels:
          tbs: eleven
      spec:
        template:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: capi
            labels:
              tbs: eleven
    - metadata:
        name: capi-deployment
        labels:
         tbs: eleven
      spec:
        secrets:
          # This must match the writeConnectionSecretToRef field
          # on the database claim; it is the name of the secret to
          # pull from the crossplane cluster, from this Application's namespace.
          - name: mysqlconn
        template:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            namespace: capi
            name: capi
            labels:
              tbs: eleven
          spec:
            selector:
              matchLabels:
                tbs: eleven
            template:
              metadata:
                labels:
                  tbs: eleven
              spec:
                containers:
                - image: hasheddan/tbs11:latest
                  name: tbs11-app
                  env:
                    - name: DB_HOST
                      valueFrom:
                        secretKeyRef:
                          name: capi-deployment-mysqlconn
                          key: endpoint
                    - name: DB_USER
                      valueFrom:
                        secretKeyRef:
                          name: capi-deployment-mysqlconn
                          key: username
                    - name: DB_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: capi-deployment-mysqlconn
                          key: password
                  ports:
                    - containerPort: 8080
                  initContainers:
                  - name: init-mysql
                    image: ubuntu:latest
                    command: ['/bin/bash', '-c', 'apt-get update && apt-get install -y mysql-client && mysql -u $DB_USER -p$DB_PASSWORD -h $DB_HOST -e "CREATE DATABASE IF NOT EXISTS capi;"']
                    env:
                      - name: DB_HOST
                        valueFrom:
                          secretKeyRef:
                            name: capi-deployment-mysqlconn
                            key: endpoint
                      - name: DB_USER
                        valueFrom:
                          secretKeyRef:
                            name: capi-deployment-mysqlconn
                            key: username
                      - name: DB_PASSWORD
                        valueFrom:
                          secretKeyRef:
                            name: capi-deployment-mysqlconn
                            key: password
    - metadata:
        name: capi-service
        labels:
          tbs: eleven
      spec:
        template:
          apiVersion: v1
          kind: Service
          metadata:
            namespace: capi
            name: capi
            labels:
              tbs: eleven
          spec:
            ports:
              - port: 80
                targetPort: 8080
            selector:
              tbs: eleven
            type: LoadBalancer