# AWS credentials secret
apiVersion: v1
kind: Secret
metadata:
  name: example-provider-aws
  namespace: crossplane-system
type: Opaque
data:
  credentials: BASE64ENCODED_AWS_PROVIDER_CREDS
---
# AWS provider that references the secrete credentials
apiVersion: aws.crossplane.io/v1alpha3
kind: Provider
metadata:
  name: aws-provider
spec:
  credentialsSecretRef:
    name: example-provider-aws
    namespace: crossplane-system
    key: credentials
  region: us-west-2
